name: bubbles
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python=3.9
  - jupyter=1.*
  - jupytext
  - numpy
  - matplotlib
  - opencv
  - poppler
  - pdf2image
  - imutils
  - scipy
  - ipython
  - black
  - pre-commit
